### ISSUE TITLE
Cannot find the "smart_battery_msgs" when doing catkin_make

### ISSUE THREAD

**Issue by princeward** [ros-gopigo/ros-node-ropigo#2]
I cannot find any anything about the "smart_battery_msg" in the source files. Where is it defined? Thanks

**Comment by christianrauch** [comment]
Which ROS version are you using? Up to jade, you need to install the Ubuntu package ros-jade-smart-battery-msgs. This is not reqired since kinetic. After this, you should be fine to install using this documentation: https://github.com/ros-gopigo/rosinstall-repo/blob/master/README.md

**Comment by princeward** [comment]
I'm using Indigo. I see the reason now. Thanks.
