### ISSUE TITLE
error install the ros-node-ropigo

### ISSUE THREAD

**Issue by wanghetongtt** [ros-gopigo/ros-node-ropigo#3]
i kept getting this error, anyone can help?

Could not find a package configuration file provided by "Gopigo" with any
  of the following names:

    GopigoConfig.cmake
    gopigo-config.cmake

Add the installation prefix of "Gopigo" to CMAKE_PREFIX_PATH or set
  "Gopigo_DIR" to a directory containing one of the above files.  If "Gopigo"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by christianrauch** [comment]
Looks like that the `gopigo` library is not installed.
Have you followed the instructions at https://github.com/ros-gopigo/rosinstall-repo?

You basically need to install the GoPiGo library either as [catkin package](https://github.com/ros-gopigo/catkin-libgopigo) or [manually](https://github.com/DexterInd/GoPiGo/tree/master/Software/C).
